"""Added new field to User model

Revision ID: 4649f0c3d678
Revises: 9b1d8a7c2ab7
Create Date: 2024-10-04 18:41:48.362491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4649f0c3d678'
down_revision: Union[str, None] = '9b1d8a7c2ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USERS', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USERS', 'password')
    # ### end Alembic commands ###
