"""Initial migration

Revision ID: 8f230412c18c
Revises: 
Create Date: 2024-10-04 18:02:58.546677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f230412c18c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USERS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_USERS_id'), 'USERS', ['id'], unique=False)
    op.create_index(op.f('ix_USERS_username'), 'USERS', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_USERS_username'), table_name='USERS')
    op.drop_index(op.f('ix_USERS_id'), table_name='USERS')
    op.drop_table('USERS')
    # ### end Alembic commands ###
